shared:
  image: hashicorp/terraform:latest
  environment:
    TF_VERSION: "1.5.0" # Specify the Terraform version
    AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID} # Environment variables for sensitive data
    ARM_CLIENT_ID: ${ARM_CLIENT_ID}
    ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET}
    ARM_TENANT_ID: ${ARM_TENANT_ID}
    ARM_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}

jobs:
  main:
    steps:
      - init: # Install dependencies
          commands:
            - apk add --no-cache curl bash jq
            - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
            - az --version
            - terraform version
            - terraform --version

      - format: # Terraform format
          commands:
            - terraform fmt -check -diff

      - init: # Terraform init
          commands:
            - terraform init

      - validate: # Terraform validate
          commands:
            - terraform validate

      - plan: # Terraform plan
          commands:
            - terraform plan -out=tfplan

      # Uncomment the below section if you want to apply the plan automatically
      # - apply: # Terraform apply
      #     commands:
      #       - terraform apply "tfplan"
